/** The column of a multi-hospital dossier row (`hospital-detail-by-facility-ids`) that holds each measure code: mirrors that template's `MAX(CASE WHEN measure_code = ...)` pivots. */
export const MEASURE_COLUMN_BY_CODE: Readonly<Record<string, string>> = {
  MORT_30_AMI: "mort_30_ami_score",
  MORT_30_HF: "mort_30_hf_score",
  MORT_30_PN: "mort_30_pn_score",
  MORT_30_COPD: "mort_30_copd_score",
  MORT_30_CABG: "mort_30_cabg_score",
  MORT_30_STK: "mort_30_stk_score",
  Hybrid_HWM: "hybrid_hwm_score",
  COMP_HIP_KNEE: "comp_hip_knee_score",
  PSI_03: "psi_03_score",
  PSI_04: "psi_04_score",
  PSI_06: "psi_06_score",
  PSI_08: "psi_08_score",
  PSI_09: "psi_09_score",
  PSI_10: "psi_10_score",
  PSI_11: "psi_11_score",
  PSI_12: "psi_12_score",
  PSI_13: "psi_13_score",
  PSI_14: "psi_14_score",
  PSI_15: "psi_15_score",
  PSI_90: "psi_90_score",
  "READM-30-AMI-HRRP": "readm_30_ami_ratio",
  "READM-30-HF-HRRP": "readm_30_hf_ratio",
  "READM-30-PN-HRRP": "readm_30_pn_ratio",
  "READM-30-COPD-HRRP": "readm_30_copd_ratio",
  "READM-30-CABG-HRRP": "readm_30_cabg_ratio",
  "READM-30-HIP-KNEE-HRRP": "readm_30_hip_knee_ratio",
  H_CLEAN_LINEAR_SCORE: "hcahps_cleanliness_score",
  H_QUIET_LINEAR_SCORE: "hcahps_quietness_score",
  H_COMP_1_LINEAR_SCORE: "hcahps_nurse_comm_score",
  H_COMP_2_LINEAR_SCORE: "hcahps_doctor_comm_score",
  H_COMP_5_LINEAR_SCORE: "hcahps_medicine_comm_score",
  H_COMP_6_LINEAR_SCORE: "hcahps_discharge_info_score",
  H_RECMND_LINEAR_SCORE: "hcahps_recommend_score",
};
